server {
    listen 8080;

    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    # catch2 CSV upload
    location /details/ {
        alias /data/details/;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_access user:rw group:rw all:r;
        create_full_put_path on;
    }

    # benchmark JSON upload
    location /benchmark/ {
        alias /data/details/benchmark/;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_access user:rw group:rw all:r;
        create_full_put_path on;
    }
}
