[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log

[program:grafana]
command=/usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini
environment=GF_SECURITY_ADMIN_PASSWORD="admin",GF_PATHS_DATA="/var/lib/grafana",GF_PATHS_PLUGINS="/var/lib/grafana/plugins",GF_PATHS_LOGS="/var/log/grafana"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/grafana.log
stderr_logfile=/var/log/supervisor/grafana_err.log

[program:watcher]
command=python3 /app/watch_new_files.py
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/watcher.log
stderr_logfile=/var/log/supervisor/watcher_err.log
