server {
    listen 8080;

    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location /details/ {
        alias /data/details/catch2/;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_access user:rw group:rw all:r;
        create_full_put_path on;
    }
}
