[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log

[program:watcher]
command=python3 /app/watch_catch2_files.py
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/watcher.log
stderr_logfile=/var/log/supervisor/watcher_err.log

[program:flask]
command=python3 /app_web/web.py
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/flask.log
stderr_logfile=/var/log/supervisor/flask_err.log
